FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
COPY prisma ./prisma/
RUN npm install
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
COPY prisma ./prisma/
RUN npm install --only=production && npx prisma generate
COPY --from=builder /app/dist ./dist
EXPOSE 5000
CMD ["npm", "start"]
